# Generated by Django 4.1.2 on 2022-11-04 01:59

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aeonium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
